name: Release scripts

on:
  push:
    tags:
      - v*

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Determine major version to publish
        id: majorver
        run: |
          tag=$(basename $GITHUB_REF)
          echo "::set-output name=major::${tag%.*.*}"
          
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          filename: 'docker-swarm-${{ steps.majorver.outputs.major }}.zip'
          path: scripts
          
      - uses: bacongobbler/azure-blob-storage-upload@v1.2.0
        with:
          source_dir: .
          container_name: swarm-scripts
          account_name: ccppi
          sas_token: ${{ secrets.SasToken }}
          extra_args: '--pattern *.zip'
          sync: false